spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:~/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false